### ISSUE TITLE
Base Functionality

### ISSUE THREAD

**Issue by markmead** [markmead/section-schema-ui#1]
- [x] Add/Edit Section Details
- [x] Add/Delete Settings
- [x] Add/Delete Blocks
- [x] Add Settings to Blocks
- [x] Move Settings to Blocks
- [x] View/Edit JSON Output
- [ ] Copy to Clipboard

**Comment by markmead** [comment]
Complete 🥳
